### ISSUE TITLE
Package information is lost when symbols are serialized to config

### ISSUE THREAD

**Issue by svetlyak40wt** [Shinmera/ubiquitous#5]
After config loading, all symbols are interned into the current package.

Because of this, it is very error prone to use something other than keywords in the path to the configuration parameter.

Example from documentation:

```
(setf (value 'something 'that 'goes 6 'levels 'deep) "Calling from the depths!")
```

is better to be written like:

```
(setf (value :something :that :goes 6 :levels :deep) "Calling from the depths!")
```

Here is a demonstration of this issue:

```lisp
CL-USER> (defun load-config ()
           (ubiquitous:restore 'test-config))
LOAD-CONFIG
CL-USER> (setf (ubiquitous:value 'the-value) 42)
42 (6 bits, #x2A, #o52, #b101010)
CL-USER> (defun get-the-value ()
           (ubiquitous:value 'the-value))
GET-THE-VALUE

CL-USER> (load-config)
#<HASH-TABLE :TEST EQUAL size 1/60 #x30200586077D>
CL-USER> (get-the-value)
42 (6 bits, #x2A, #o52, #b101010)
T
CL-USER> (in-package #:blah)
#<Package "BLAH">
BLAH> (cl-user::load-config)
#<HASH-TABLE :TEST EQUAL size 1/60 #x3020058CE3DD>
BLAH> (cl-user::get-the-value)
NIL
NIL
BLAH> (alexandria:hash-table-plist #v117)
(COMMON-LISP-USER::THE-VALUE 42)
BLAH> (alexandria:hash-table-plist #v120)
(THE-VALUE 42)
BLAH> 
```

Here `#v117` refers to a line where `load-config` was called within `CL-USER` package, and `#v120` were it was called within `BLAH` package.

I've lost some time trying to figure out why my config works when I restore it from the repl, and doesn't (have no any values) when it is restored by a program, started from the command line.

**Comment by svetlyak40wt** [comment]
Probably, it is not a reader's problem, but a writer's problem and it should keep package prefixes for symbols. Always.

**Comment by svetlyak40wt** [comment]
Found a solution: http://lisptips.com/post/20871695085/printing-package-qualified-symbols

**Comment by Shinmera** [comment]
I wonder if it would be possible to fix this by writing in a header that sets the package of the file. This would be compatible with existing files, and would retain the short-form notation for symbols in the home package.

**Comment by svetlyak40wt** [comment]
Do you mean that this code:

```lisp
(in-package :app)
(restore 'my-config)
(setf (value 'path) "/home/art/test-app/")

(in-package :foo)
(setf (value 'index) 1)

(in-package :bar)
(setf (value 'name) "Alex")
```

should produce such config:

```
app
[hash-table equal (
    (path . "/home/art/test-app/")
    (foo::index . 1)
    (bar::name . "Alex")
)]
```
I think this is doable, but how does it solve the problem of the already written configs?

By the way, why do you think that changing this format will be an incompatible with existing configs? The reader was unchanged and is able to work with both package qualified and non qualified symbols.

**Comment by Shinmera** [comment]
No, I mean that it would produce
```
; package APP
[hash-table equal (
    (path . "/home/art/test-app/")
    (foo::index . 1)
    (bar::name . "Alex")
)]
```
This would be backwards-compatible.

As I mentioned in my follow-up comment, your idea is not incompatible, but it forces all symbols printed in the representation to become far more verbose than before, which is a hindrance in terms of human readability and editability. That's why I'm not very enthusiastic about it.

**Comment by svetlyak40wt** [comment]
```
; package APP
[hash-table equal (
    (path . "/home/art/test-app/")
    (foo::index . 1)
    (bar::name . "Alex")
)]
```
This code is not very different from:

```
app
[hash-table equal (
    (path . "/home/art/test-app/")
    (foo::index . 1)
    (bar::name . "Alex")
)]
```
However the latter is readable by standard reader as two lisp forms.
May be it makes sence to add a third form like:

```
(version 1)
(in-package app)
[hash-table equal (
    (path . "/home/art/test-app/")
    (foo::index . 1)
    (bar::name . "Alex")
)]
```

Then if reader reads first form, and it is not like `(version xxx)`, then the version is 0, otherwise we know the format's version and can do different things depending on it.

If you wish, I could reopen and improve my pull request to support such behaviour.

**Comment by Shinmera** [comment]
The latter is *not* backwards compatible with the previous way of reading the data, as ubiquitous only reads in one form. The comment is compatible because the reader simply skips over it.

**Comment by svetlyak40wt** [comment]
Why it is not backwards compatible? A new reader will be able to read old configs with one form and a new configs, with many forms. Do I miss something?

**Comment by Shinmera** [comment]
Because old versions of ubiquitous won't be able to read the files.

**Comment by svetlyak40wt** [comment]
That is right.

**Comment by svetlyak40wt** [comment]
Good idea!
