### ISSUE TITLE
Make CONFIG-DIRECTORY parametrizable

### ISSUE THREAD

**Issue by phoe** [Shinmera/ubiquitous#7]
Currently, `CONFIG-DIRECTORY` returns a constant value, which means that configurations for multiple systems utilizing Ubiquitous can collide with each other.

I would like to select a different config directory for an application I am writing, based either on a parameter to that function, or the value of some special variable that I am allowed to rebind.

**Comment by Shinmera** [comment]
No they can't collide, if you use a fully qualifed symbol, as the documentation says you should.

You can also just pass an explicit path if you want to control where things go yourself.
