### ISSUE TITLE
Unsure how to use Ubiquitous from Roswell scripts

### ISSUE THREAD

**Issue by duncan-bayne** [Shinmera/ubiquitous#9]
I have a Common Lisp project with two Roswell scripts.  I'd like one script to persist state using Ubiquitous, and have the _other_ script read it.

```
scripts
├── download-messages.ros
└── email-messages.ros
```

The challenge is that Roswell initializes each script with its own package.  So if I `restore`, I get a separate Ubiquitous data store for each script.  E.g.:

```
(in-package :ros.script.email-messages.3790925476)
(ubiquitous:restore 'keep-me)
```

... which leads to:

```
; meta (:version 1.0 :package "ROS.SCRIPT.EMAIL-MESSAGES.3790925476")
[hash-table equal (:downloaded-message-ids nil) (:sent-message-ids nil)]
```

I _could_ use the same package for both scripts, but that seems weird.  How do you propose I best handle this requirement with Ubiquitous?

**Comment by Shinmera** [comment]
Just use a string for the designator.

**Comment by duncan-bayne** [comment]
Thanks @Shinmera :)
